spring:
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/sipe
      username: root
      password: 1234
      driver-class-name: com.mysql.jdbc.Driver
